# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MicroPython package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install MicroPython
      run: |
        sudo snap install micropython
        /snap/bin/micropython -m upip install micropython-socket
        /snap/bin/micropython -m upip install micropython-unittest
    - name: Test
      run: |
        /snap/bin/micropython tests.py
